### ISSUE TITLE
TypeError: 'in <string>' requires string as left operand, not dict

### ISSUE THREAD

**Issue by micheljung** [FAForever/QAI#51]
```Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/opt/stable/QAI/qai_plugin.py", line 143, in on_privmsg
    if reactionword in lowercaseMsg:
TypeError: 'in <string>' requires string as left operand, not dict
```

**Comment by Bra1nwash3d** [comment]
fixed a while ago in https://github.com/FAForever/QAI/commit/06c924b7b82a1cc5ce1bd8c843c1f2e8f5f6c30e
